source "https://rubygems.org"

gem 'cucumber'
gem 'capybara', '2.13.0'
gem 'selenium-webdriver', '2.53.4'
gem 'rspec'
gem 'site_prism'
gem 'geckodriver-helper'
# gem 'faker'
gem 'cpf_faker'
gem 'faker', github: 'stympy/faker'
